version: "3"


services:
  auth-db:
    image: postgres:15
    volumes:
      - ./db/auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  auth-server:
    build:
      context: ./auth
    command: "bash /app/runserver.sh"
    volumes:
      - ./auth:/app/
    environment:
      - POSTGRES_HOST=auth-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=auth-db
      - SECRET_KEY=SECRET_KEY
      - HOST=auth-server
      - PORT=8000
    links:
      - auth-db

  contents-db:
    image: postgres:15
    volumes:
      - ./db/contents:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=contents-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - 5432:5432

  contents-server:
    build:
      context: ./contents
    command: "bash /app/runserver.sh"
    volumes:
      - ./contents:/app/
    environment:
      - POSTGRES_HOST=contents-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=contents-db
      - SECRET_KEY=SECRET_KEY
      - HOST=contents-server
      - PORT=8000
    links:
      - contents-db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - auth-server
      - contents-server
