"""migrate at the docker

Revision ID: 54837828c32b
Revises: 
Create Date: 2024-03-06 20:17:53.680982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54837828c32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('modified_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
