"""migrate at the docker

Revision ID: b3e269c45f45
Revises: 54837828c32b
Create Date: 2024-03-06 22:05:55.354718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e269c45f45'
down_revision = '54837828c32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=50), nullable=True))
        batch_op.drop_column('modified_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('modified_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review')

    # ### end Alembic commands ###
